rem MA64 class ver 0.1

field private d00,d01,d02,d03
field private d04,d05,d06,d07
field private d08,d09,d0a,d0b
field private d0c,d0d,d0e,d0f
field private d10,d11,d12,d13
field private d14,d15,d16,d17
field private d18,d19,d1a,d1b
field private d1c,d1d,d1e,d1f
field private d20,d21,d22,d23
field private d24,d25,d26,d27
field private d28,d29,d2a,d2b
field private d2c,d2d,d2e,d2f
field private d30,d31,d32,d33
field private d34,d35,d36,d37
field private d38,d39,d3a,d3b
field private d3c,d3d,d3e,d3f
